# Site settings
title: RainbowMarks Photography
shorttitle: "RainbowMarks.com"
email: "rainbowmarks@christoc.com"
description: "RainbowMarks Photography, specializing in event photography in and around St. Louis Missouri."
url: https://rainbowmarks.com
baseurl: 
facebook_username: "rainbowmarksphoto"
twitter_username: "rainbowmarks"
instagram_username: "RainbowLandMarks"
github_username:
deviantart_username: 
flickr_username: "chammond"
discus_shortname: "rainbowmarks"
share: true
google_analytics: G-6V585TFXGW # UA-69145-51
favicon: favicon.ico
data_dir: _data

# Owner/author information
owner:
  name: Chris Hammond
  avatar: 2022_ChrisHammond_200.jpg
  
  info: RainbowMarks Photography based out of Wildwood, MO. Specializing in automotive, sports, events, action, landscapes and of course Rainbows. 

authors:
   ChrisHammond:
    name: Chris Hammond
    display_name: Chris Hammond
    first_name: Chris
    last_name: Hammond
    gravatar: bff097b7cc348bebce39ee1c7694d125
    email: rainbowmarks@christoc.com
    web: https://www.chrishammond.com
    twitter: https://twitter.com/collectorofjack
    description: "<a href=\"https://www.chrishammond.com\">Chris</a> has been collecting Jack Daniel's for 26 years and uses this site to document his collection. <a href=\"/JackDanielsCollector\">Read more about his story</a>"




# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments:
  provider: false # disqus
  disqus:
    short_name: # "rainbowmarks"

# Internal nav
nav:
  - MR340: "/mr340/2024"
  - BLOG: "/blog/"
  - GALLERIES: "https://photos.rainbowmarks.com/"
  - EVENTS: "/events/"
 # - PURCHASE: "/purchase/"
  - ABOUT: "/about/"
  - SHOP: "https://photos.rainbowmarks.com/"
  

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination: ./_site
port: 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"
permalink: "/blog/:title/"
categories_path: "/blog/category/"
tags_path: "/blog/tag/"
# Plugins
plugins:
 - jekyll-paginate
 - jekyll-feed
 - jekyll-archives
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md",vendor]

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/blog/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

#jekyll_picture_tag

picture:
  suppress_warnings: true
  fast_build: true
  # source: img/
  output: generated/

# gallery page generation
# gallery page generation
defaults:
  - scope:
      type: galleryimage  # select all galleryimage pages
    values:
      layout: picture
  - scope:
      path: ""  # An empty string here means all files
      type: "posts"
    values:
      author: "ChrisHammond"

exclude:
  - /img/portfolio/*
  - /img/posts/*
  - /img/slider/*
  - /img/journal/*